version: '3.8'

services:
  db:
    build: .
    container_name: postgres-db
    restart: always
    tty: true
    ports:
      - 5433:5432
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sic2222
      - POSTGRES_DB=projectdb
